### ISSUE TITLE
Upload Image for Nested Components

### ISSUE THREAD

**Issue by Car-Tik9** [SoftwareBrothers/adminjs#778] opened 2021-02-27 19:13 UTC
**Describe the bug**
Hi Team,
I have Nested Schema with one property as Array of Objects.
I could see  addItem in the admin panel but when I click the addItem I want to have an extra upload Image component for each Item.
Could you please help me How can I do that.
I have tried using modifying the options but no luck

**Installed libraries and their versions**

"@admin-bro/express": "^3.0.1",
"@admin-bro/mongoose": "^1.0.0",
"admin-bro": "^3.2.5"... mongo, express (whatever you think is relevant)

**To Reproduce**
1. Create a nested schema with array as type
2. Add custom component in options of config

**Expected behavior**
I want upload Image component to be shown in each addItem of admin panel
**Screenshots**

![Screenshot 2021-02-28 at 12 37 52 AM](https://user-images.githubusercontent.com/23266926/109397608-8c6ff900-795d-11eb-9249-c6388becf400.png)

**AdminBroOptions with schema**
Paste your AdminBro config with database schema if it could be related to the issue
const adminBro = new AdminBro({
    resources: [
      {
        resource: SuccessStories,
        options
      },
      {
        resource: BoardMembers,
        options
      },
      {
        resource: Homepage,
        properties:{
          featuredCauses:{
            components:{
              edit:AdminBro.bundle('../components/ImageUrl.tsx')
            }
          }
        },
        actions:{
          new:{
            after:uploadImageAfterHook,
            before:uploadImageBeforeHook
          },
          edit:{
            after:uploadImageAfterHook,
            before:uploadImageBeforeHook
          },
          delete:{
            after:uploadImageHook
          }
        }
      },
      {
        resource: Events,
        options
      },);
**Desktop (please complete the following information if relevant):**
 - OS: [iOS]
 - Browser [chrome, safari]
 - Version [22]

Please do let me know If you any further information for clear understanding
Thanks

**Comment by dziraf** [comment] 2021-12-28 10:33
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:33 UTC
