### ISSUE TITLE
SelectDropDown option don't strict filter

### ISSUE THREAD

**Issue by anthlasserre** [SoftwareBrothers/adminjs#830] opened 2021-04-30 15:23 UTC
**Describe the bug**
From Drawer Filter tried to select an item from SelectDropDown. Options of SelectDropDown are `['FEMALE', 'MALE']`.
When I select `MALE` my list items are composed of MALE & FEMALE 🤷🏼‍♂️.
What I think it is the word **MALE** is in **FEMALE**.
How I can do to strict filter items with **MALE** option ?

**Installed libraries and their versions**

* @admin-bro/express@3.0.1
* admin-bro@3.3.1
* admin-bro-expressjs@2.1.1
* admin-bro-mongoose@0.5.2
* express@4.17.1
* mongodb@3.6.3
* mongoose@5.11.8
* mongoose-seed@0.6.0

**To Reproduce**
1. Go to any Collection in Navigation (left side)
2. Click on **Filter** button on top right
2. On Drawer, select option **MALE** on **gender** SelectDropDown
3. Click on **Apply changes**

**Expected behavior**
I would like to have a strict filter on what I select

**Screenshots**
![image](https://user-images.githubusercontent.com/28066214/116716754-6952db80-a9d8-11eb-96bc-512f52f0e858.png)

**Desktop (please complete the following information if relevant):**
 - Browser [chrome]
 - Version [90.0.4430.93]

**Comment by dziraf** [comment] 2021-12-28 10:19
Currently not doable unless you override list action handler. Adapters use `LIKE` for `string` type filters by default (or mongodb equivalent).

Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:19 UTC
