### ISSUE TITLE
Error when editing entities.

### ISSUE THREAD

**Issue by GuitarWag** [SoftwareBrothers/adminjs#716] opened 2020-12-15 22:08 UTC
**Describe the bug**
It's a simple KOA server with TypeORM entities.
When I edit any resource, an insert command instead of an update runs a give an error:

**Installed libraries and their versions**

 "admin-bro": "^3.3.1",
    "@admin-bro/koa": "^1.1.1",
    "@admin-bro/typeorm": "^1.4.0",

**To Reproduce**
1. Go to any edit and change any data
2. Click on save
4. See error and on terminal de wrong SQL that has run.

**Expected behavior**
Edit ends with success

**Terminal**
19:05:44 DEBUG koa Request POST /admin/api/resources/Organization/records/1/edit
query failed: INSERT INTO `organization`(`id`, `version`, `created_at`, `created_by`, `updated_by`, `updated_at`, `deleted_at`, `deleted_by`, `type`, `name`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) -- PARAMETERS: ["1",1,"2020-12-15T22:04:05.617Z",1,0,"2020-12-15T22:04:05.617Z",null,0,"sponsor","Samsung1"]
error: Error: Duplicate entry '1' for key 'PRIMARY'
    at Packet.asError (/Users/wagner-lagoasoft/dev/mmw/monorepo/node_modules/mysql2/lib/packets/packet.js:712:17)
    at Query.execute (/Users/wagner-lagoasoft/dev/mmw/monorepo/node_modules/mysql2/lib/commands/command.js:28:26)
    at PoolConnection.handlePacket (/Users/wagner-lagoasoft/dev/mmw/monorepo/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/Users/wagner-lagoasoft/dev/mmw/monorepo/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/wagner-lagoasoft/dev/mmw/monorepo/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/wagner-lagoasoft/dev/mmw/monorepo/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry '1' for key 'PRIMARY'"
}
**AdminBroOptions with schema**

 branding: {
          companyName: 'Company',
        },

**Comment by adikalon** [comment] 2021-01-17 14:55
I have this problem with nest.

My libraries:
"admin-bro": "^ 3.3.1",
"@ admin-bro / nestjs": "^ 1.0.0",
"@ admin-bro / typeorm": "^ 1.4.0",

**Comment by TigerWest** [comment] 2021-03-21 07:22
i have same issue...
but i think that this is not admin-bro issue

If you are using the primary column as a bigint, you should apply the correct transformer.

https://github.com/typeorm/typeorm/issues/2400

export const bigint: ValueTransformer = {
  to: (entityValue: number) => entityValue,
  from: (databaseValue: string): number => parseInt(databaseValue, 10)
}

@Entity()
export class User {
  @Generated('increment')
  @PrimaryColumn('bigint', { transformer: [bigint] })
  id: number;

}

**Comment by zenghj** [comment] 2021-04-27 03:39
I have same issue
```
  @PrimaryGeneratedColumn({
    type: 'bigint',
    name: 'id',
    comment: 'ID',
    unsigned: true,
  })
  id: string;
```

while editing , i got a error 
```
{
// some other info
    "errors": {
      "undefined": {
        "type": "QueryFailedError",
        "message": "ER_DUP_ENTRY: Duplicate entry '8' for key 'PRIMARY'"
      }
    },
    "id": "8",
}
```

**Comment by dziraf** [comment] 2021-12-28 10:42
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:42 UTC

**Comment by jeybee** [comment] 2022-02-26 20:59
This is still an issue today. Can't save an edit for any entity with a bigint.

A sequelize column specified as this will produce a validation error:
```@Unique
@AllowNull(false)
@Column(DataType.BIGINT)
public_id!: bigint;```
