### ISSUE TITLE
Property with type 'number' accepts nondigital signs

### ISSUE THREAD

**Issue by yaroslavyal** [SoftwareBrothers/adminjs#819] opened 2021-04-19 09:30 UTC
When I define the type of property as `number`, the frontend displays a standard text field, where I can type nondigital signs. Additionally, on saving frontend sends value as a string to the backend.

**Installed libraries and their versions**

* admin-bro@4.0.0
* @admin-bro/nestjs@1.1.0
* @admin-bro/typeorm@1.4.0
* @admin-bro/express@3.1.0

**To Reproduce**
1. Create a resource with property `number` or `float`
2. Check type of input for this field

**Expected behavior**
Frontend displays input, which accepts only digits

**Comment by yaroslavyal** [comment] 2021-06-16 10:42
any updates?

**Comment by AlexanderBich** [comment] 2021-09-13 09:45
As a temprorary work around you can pass:
```
      total: {
        type: 'number',
        props: {
           type: 'number',
        }
      },
 ```

**Comment by dziraf** [comment] 2021-12-28 10:29
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:29 UTC

**Comment by Ameendarwan** [comment] 2022-03-30 05:28
> Closing because the issue is old. If you still need help, please reopen.

I need help. Property 'number' and 'Float' both accept characters. It must accept only digits.
