### ISSUE TITLE
Create/Update nested associatons

### ISSUE THREAD

**Issue by alvaropaco** [SoftwareBrothers/adminjs#829] opened 2021-04-30 15:07 UTC
I've a Postgres database with 3 tables in my schema: User, Name and Phone. I'm using sequelize as the ORM, and I've mapped the relation between these 3 tables as reference fields. My schemas are: 

Phone 
```
sequelize.define('Phone', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    number: {
      type: DataTypes.STRING,
      validate: {
        len: {
          args: [2, 11],
          msg: 'The phone number must be a maximum of 11 characters.',
        },
      },
      get() {
        const number = this.getDataValue('number');
        return number || ' ';
      },
    },
    type: {
      type: DataTypes.STRING,
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    underscored: true,
    tableName: 'phone',
    timestamps: false,
  });
```

Name
```
sequelize.define('Name', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    salutation: {
      type: DataTypes.STRING,
    },
    first: {
      type: DataTypes.STRING,
    },
    middle: {
      type: DataTypes.STRING,
    },
    last: {
      type: DataTypes.STRING,
    },
    suffix: {
      type: DataTypes.STRING,
    },
    preferred_first: {
      type: DataTypes.STRING,
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    underscored: true,
    tableName: 'name',
    timestamps: false,
  })
```

User
```
sequelize.define('UserInternal', {
    id: {
      type: DataTypes.UUIDV4,
      autoIncrement: true,
      primaryKey: true,
    },
    email: {
      type: DataTypes.STRING,
    },
    name: {
      type: DataTypes.UUID,
      field: 'name_id',
      references: {
        model: 'name',
        key: 'id',
      },
    },
    phone: {
      type: DataTypes.UUID,
      field: 'phone_id',
      references: {
        model: 'phone',
        key: 'id',
      },
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    underscored: true,
    tableName: 'user_internal',
    timestamps: false,
    indexes: [],
  });
```

This is working well and is rendering with the appropriated name and phone for the user. But, my problem is that in the creation/update for the field for Name and Phone are dropbox menu with autocomplete. I want to let this field as a String and when I fill the field and save, the AdminBro creates a new record for the Name and Phone and associate with the new User record:
![FireShot Capture 048 - Company - localhost](https://user-images.githubusercontent.com/3423410/116714628-54f8e980-a9ac-11eb-93c2-9af1a5b32c04.png)
![FireShot Capture 051 - Company - localhost](https://user-images.githubusercontent.com/3423410/116714665-5e825180-a9ac-11eb-9189-579c92837d14.png)

Is possible to do that?

**Comment by dziraf** [comment] 2021-12-28 10:26
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:26 UTC
