### ISSUE TITLE
404 on list action for model/view without primary key

### ISSUE THREAD

**Issue by bifot** [SoftwareBrothers/adminjs#708] opened 2020-12-13 14:14 UTC
**Describe the bug**

404 status on `/admin/api/resources/:name/actions/list`

**Installed libraries and their versions**

```
    "@admin-bro/koa": "^1.1.1",
    "@admin-bro/sequelize": "^1.1.1",
    "admin-bro": "^3.3.1",
    "pg": "^8.5.1",
    "sequelize": "^6.3.5"
```

**To Reproduce**

1. Create view without primary key `id`
2. Request `/admin/api/resources/:name/actions/list`
3. See logs: `SELECT "id", ...`

**Expected behavior**

1. 200 HTTP
2. Correct query without not defined field

**Comment by bifot** [comment] 2020-12-13 14:19
My bad, will use `removeAttribute` on my model.

**Comment by bifot** [comment] 2020-12-13 14:28
Actually, I was right - https://github.com/SoftwareBrothers/admin-bro/blob/master/src/backend/adapters/record/base-record.ts#L182

After attributes renovation, an error happens again.

**Comment by dziraf** [comment] 2020-12-13 15:13
Primary key is required because whole admin-bro depends on it for finding records and filtering, i. e. bulk delete. Composite keys won't work here. I personally just add an auto-generated PK for i. e. junction tables

**Comment by bifot** [comment] 2020-12-13 16:49
I prefer to select needed fields for filters by myself (in my example it's user id of view balances). But with admin-bro it's impossible how I understand it. Also, I don't understand why I didn't receive any logs in the process about this error, but endpoint returned 404.

**Comment by platform-kit** [comment] 2020-12-19 20:44
I'm also getting a 404 on the list route for my resource. It has a primary key in the DB and in the sequelize model. Browser console says 

```GET http://localhost:3333/administrate/api/resources/users/actions/list 404 (Not Found)```

Console output:

```[Object: null prototype] {}```

**Comment by bifot** [comment] 2020-12-30 11:30
@platform-kit, it's absolutely not production-ready solution. I didn't find the way how to handle internal errors from admin-bro and I was debugging via source code of admin-bro, adding try/catch by myself. Getting 404 error (not found) on internal library errors is really bad.

**Comment by dziraf** [comment] 2021-12-28 10:43
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:43 UTC

**Comment by bifot** [comment] 2021-12-28 11:05
Too old? Did you fixed this?

**Comment by haplo** [comment] 2022-09-29 17:02
> @dziraf Do you have any other solution than adding an AI field over multiple-columns primary key?

I also reached this issue because I have a M2M table that wanted to have in AdminJS, and it was failing because it has a composite primary key made of two columns. Is AdminJS never going to support composite keys? Having to add another primary key field is a hack in my opinion.

**Comment by dziraf** [comment] 2022-09-29 17:54
how do you expect in-app routing to work with composite keys? currently `recordId` is a single identifier

**Comment by haplo** [comment] 2022-10-07 13:46
> how do you expect in-app routing to work with composite keys? currently `recordId` is a single identifier

I'm not intimate with AdminJS internals, but could `recordId` be a list with the primary key columns?

**Comment by Coinhexa** [comment] 2024-04-22 17:37
> how do you expect in-app routing to work with composite keys? currently `recordId` is a single identifier

what would be the issue if recordId was an Array instead?

**Comment by dziraf** [comment] 2024-04-22 20:56
This is currently not possible as it would require us to rewrite how both querying works on adapter level and how in-app routes are composed:

1. Changes in core `adminjs` to abstract BaseResource structure
2. Changes in every adapter (`@adminjs/prisma`, `@adminjs/sql`, `@adminjs/typeorm`, `@adminjs/sequelize`, `@adminjs/mongoose`, `@adminjs/objection`, `@adminjs/mikro-orm`, `@adminjs/adonis`) so that they use updated `BaseResource` and build queries with composite keys
3. Update how routes are built in the frontend. Simple array or hyphen separated IDs are not enough since AdminJS needs to know which ID refers to which key.

This is not something we're willing to do anytime soon, most likely this is something that could happen if we decide to push other large changes that touch adapters/querying logic, i. e. rebuilding filters in AdminJS. If you worry about data integrity in junction tables, you can create unique indexes on multiple columns to ensure foreign key combinations are unique.
