### ISSUE TITLE
Change name of the fields from table

### ISSUE THREAD

**Issue by RudrikaJnext** [SoftwareBrothers/adminjs#812] opened 2021-04-13 05:56 UTC
I have tried to change the field from the displayed table, referred: https://adminbro.com/AdminBroOptions.html#locale

Here, Items is the Resource name as well as a model name, and ownerid is the property.

![image](https://user-images.githubusercontent.com/82202278/114503512-10025280-9c4b-11eb-9816-5cae9e4a28e6.png)
![ColumnChange](https://user-images.githubusercontent.com/82202278/114503543-1e506e80-9c4b-11eb-9a28-1b8678a82cc0.png)

It still remains same. Is there any alternate way to do that?

**Comment by ahsanz024** [comment] 2021-07-12 13:27
@RudrikaJnext possible duplicate? https://github.com/SoftwareBrothers/adminjs/issues/800

**Comment by dziraf** [comment] 2021-12-28 10:30
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:30 UTC
