### ISSUE TITLE
Can i use Number for mongoose ref?

### ISSUE THREAD

**Issue by l4kk3r** [SoftwareBrothers/adminjs#883] opened 2021-07-14 09:11 UTC
When i have my mongoose _id's as Numbers (1, 2, 3, 4, 5) and trying to make {
type: Number,
ref: 'Model
}
Admin bro cant make these relations, it does not make select box. But when i change _id to ObjectId's it makes relationships and select box is vizible.

Is there any way to create relations in Admin Bro if my _id is Number ?

**Comment by l4kk3r** [comment] 2021-07-14 09:15
![image](https://user-images.githubusercontent.com/66743739/125596472-2553d4fe-69e7-437d-8082-8f068705da3b.png)
![image](https://user-images.githubusercontent.com/66743739/125596524-525173c3-8c9f-4987-93e5-0da040e538b6.png)
![image](https://user-images.githubusercontent.com/66743739/125596618-7571c02b-904f-40e8-9f60-82eee8ed9ca7.png)

Using Number for _id is a valid method
![image](https://user-images.githubusercontent.com/66743739/125596755-b239ed36-fe81-42d1-a156-250215e1c2f5.png)

**Comment by dziraf** [comment] 2021-12-28 10:14
Closing because the issue is old. If you still need help, please reopen (preferrably in `adminjs-mongoose` repository)

**Closed by dziraf** 2021-12-28 10:14 UTC
