### ISSUE TITLE
I have an inquiry in the resource section.

### ISSUE THREAD

**Issue by kir931028** [SoftwareBrothers/adminjs#753] opened 2021-02-02 02:11 UTC
```
collection: FireStore.collection(`Room`),
  schema: {
    contents: 'string',
    see: 'boolean',
    uid: 'reference',
  },
```
I am creating a resource like this right now. 
However, the collection is a sub-collection, so in order to fetch data, the doc id of the parent collection is required. 
I succeeded in getting the id value of the parent element through the link by query, but the element was 
```
FireStore.collection(`Chat/${chatId}/Room`),
```

It keeps failing to switch to.
Is there a way to get the query right away?
If that doesn't work, is there any way I can help you with this?

**Comment by dziraf** [comment] 2021-12-28 10:37
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:37 UTC
