### ISSUE TITLE
Login page not working @^6

### ISSUE THREAD

**Issue by theprometeus** [SoftwareBrothers/adminjs#1194] opened 2022-07-27 21:41 UTC
**Describe the bug**
The login page is trying to render a box that contains a `lineHeight` attribute that is not found in the current version along with other options, and can't be overriden in the styling options.

**Installed libraries and their versions**

* adminjs@^6
* express

**To Reproduce**
1. Create a project with an express router
2. Use the authenticated router
3. Try to access the login page

**Screenshots**
![image](https://user-images.githubusercontent.com/3390576/181377576-6c1298f2-c244-4adc-bf7a-2a2bdf2e7914.png)

**Smartphone (please complete the following information if relevant):**

**Additional context**
Works find with adminjs@^5

**Comment by theprometeus** [comment] 2022-07-27 21:43
Also I have tried to downgrade to adminjs@^5 and use the latest design-system version with the `adminjs.bundle` function, but, unfortunatelly, it is trying to bundle using the design-system version packaged with the adminjs package.

**Comment by dziraf** [comment] 2022-07-28 06:50
This is the same issue as this: https://github.com/SoftwareBrothers/adminjs/issues/1180#issuecomment-1190293422

Not sure what caused this since we updated those libraries like we'd normally do, it might be some versioning issue on their end

**Comment by almandoro** [comment] 2022-07-30 21:33
I also run into this error

@theprometeus as dziraf mentioned, have a look here -> https://github.com/SoftwareBrothers/adminjs/issues/1180#issuecomment-1190293422

Implicitly adding these dependencies resolved this problem
`yarn add react@^18.1.0 react-dom@^18.1.0 styled-components@^5.3.5`

**Comment by dziraf** [comment] 2022-08-01 05:49
This might be caused by our other dependencies, I'm currently working on upgrading them.

**Comment by krzysztofstudniarek** [comment] 2022-08-16 09:39
It is a duplicate of https://github.com/SoftwareBrothers/adminjs/issues/1180#issuecomment-1190293422

**Closed by krzysztofstudniarek** 2022-08-16 09:39 UTC
