### ISSUE TITLE
NoResourceAdapterError: There are no adapters supporting one of the resource you provided

### ISSUE THREAD

**Issue by jaiyush2020** [SoftwareBrothers/adminjs#768] opened 2021-02-16 12:41 UTC
"@admin-bro/express": "^3.1.0",
 "@admin-bro/mongoose": "^1.1.0",
 "admin-bro": "^3.4.0",
"express": "^4.17.1",
 "express-formidable": "^1.2.0",

Ubuntu 20.04

Ubunut, Nodejs, Express, MongoDB

const AdminBro = require('admin-bro');
const AdminBroExpress = require('@admin-bro/express');
const AdminBroMongoose = require('@admin-bro/mongoose');
const mongoose = require('mongoose');
const express = require('express');
const app = express();

AdminBro.registerAdapter(AdminBroMongoose);

const run = async () => {
    try {
        const mongooseDb = await mongoose.connect('mongodb://localhost/quiz', {useNewUrlParser: true, useUnifiedTopology: true});
        const adminBro = new AdminBro({
            databases: [mongooseDb],
            rootPath: '/admin',
            resources: [User,], 
    
        })
    
        const router = AdminBroExpress.buildRouter(adminBro);
        app.use(adminBro.options.rootPath, router);
    }
    catch(e) {
        console.log(e);
    }
  }

  run()

**Comment by sirramin** [comment] 2021-07-22 00:08
same error

**Comment by marwenbk** [comment] 2021-11-23 19:50
same issue

**Comment by dziraf** [comment] 2021-12-28 10:35
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:35 UTC
