### ISSUE TITLE
Show Object type property from MongoDB document

### ISSUE THREAD

**Issue by guidopontet** [SoftwareBrothers/adminjs#686] opened 2020-11-15 15:16 UTC
Hi, i am unable to display a value of my mongoose model:

```
  extraData: {
    type: Object,
  },
```
It is showing like an empty value:

![image](https://user-images.githubusercontent.com/27219728/99188674-f8767a80-273b-11eb-8708-95e2fe286805.png)

**Dependencies:**
    "@admin-bro/express": "^3.0.1",
    "@admin-bro/mongoose": "^1.1.0",
    "admin-bro": "^3.3.1",

**Expected behavior**
Show json or object from MongoDB

**Comment by imnaveenk** [comment] 2021-09-17 20:40
+1

**Comment by dziraf** [comment] 2021-12-28 10:47
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:47 UTC
