### ISSUE TITLE
Bundle problem -Custom component undefined !

### ISSUE THREAD

**Issue by roeigr7** [SoftwareBrothers/adminjs#729] opened 2021-01-05 21:23 UTC
admin-bro 3.3.1
i try to build custom component :
in the options:

    const options = {
	properties: {
		photo: {
			components: {
				edit: AdminBro.bundle("../../src/photo"),//the path is right !
			},
		},
	},
};

the photo edit componenet:

    import React from "react";
    const Edit = () => {
	return <div>hello</div>;
     };
    export default Edit;

and the created entry of admin bro:

    AdminBro.UserComponents = {}
    import Component1 from '../controllers/resources/photo'
    AdminBro.UserComponents.Component1 = Component1
i dont know why i get:

    Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `BasePropertyComponent`.
See development console for more details...

.

    react_devtools_backend.js:2430 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `BasePropertyComponent`........

**Comment by SimonB407** [comment] 2021-01-26 15:20
This path `AdminBro.bundle("../../src/photo")` and this path `import Component1 from '../controllers/resources/photo'` are different. Either you copied this code in different times and meanwhile you did some change, or something is not right. You can try and delete .admin-bro directory.

**Comment by kevseroz** [comment] 2021-03-31 08:12
@roeigr7 any luck solving this problem? I have the same problem and I don't know what should I do.

**Comment by amethystdeceiver** [comment] 2021-05-31 13:57
@roeigr7 @kevseroz is your component file a .jsx? I've had this issue when I used .js for the extension by mistake.

**Comment by captixn** [comment] 2021-08-31 16:28
I have also the same issue with the following basic code:

**CustomJSONViewer.tsx**

```` javascript
import React from "react";
import { InputGroup, Label } from "@admin-bro/design-system";

const CustomJSONViewer = (props) => {
  const { record, property } = props;
  const value = record.params[property.path];
  return (
    <InputGroup>
      <Label>{property.label}</Label>
      {JSON.stringify(value)}
    </InputGroup>
  );
};

**export default CustomJSONViewer;**
````

**admin-bro-setup.ts**
``` javascript
  const Feedback: ResourceWithOptions = {
    resource: FeedbackModel,
    options: {
      properties: {
        infos: {
          isVisible: {
            list: false,
            edit: true,
            filter: false,
            show: true,
          },
          components: {
            show: AdminBro.bundle('./CustomJSONViewer'),
          },
        },
    },
  };
```

Both files are on the same path. 

According to the documentation, it should work! 
https://adminbro.com/BasePropertyComponent.html

admin-bro version:  3.4.0

**Comment by captixn** [comment] 2021-08-31 16:58
> I have also the same issue with the following basic code:
> 
> **CustomJSONViewer.tsx**
> 
> ```js
> import React from "react";
> import { InputGroup, Label } from "@admin-bro/design-system";
> 
> const CustomJSONViewer = (props) => {
>   const { record, property } = props;
>   const value = record.params[property.path];
>   return (
>     <InputGroup>
>       <Label>{property.label}</Label>
>       {JSON.stringify(value)}
>     </InputGroup>
>   );
> };
> 
> **export default CustomJSONViewer;**
> ```
> 
> **admin-bro-setup.ts**
> 
> ```js
>   const Feedback: ResourceWithOptions = {
>     resource: FeedbackModel,
>     options: {
>       properties: {
>         infos: {
>           isVisible: {
>             list: false,
>             edit: true,
>             filter: false,
>             show: true,
>           },
>           components: {
>             show: AdminBro.bundle('./CustomJSONViewer'),
>           },
>         },
>     },
>   };
> ```
> 
> Both files are on the same path.
> 
> According to the documentation, it should work!
> https://adminbro.com/BasePropertyComponent.html
> 
> admin-bro version: 3.4.0

Fixed! I had to manually delete the .adminBro folder. 

I suggest the following fix: delete/regenerate .adminBro when user components change.

**Comment by mniemiec92** [comment] 2021-11-16 17:54
Anyone has still this issue? Deleting .adminBro folder didn't help in my case. Error started to occurred when I've update adminBro package version.

**Comment by dziraf** [comment] 2021-12-28 10:41
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:41 UTC
Labels: help wanted
