### ISSUE TITLE
"Join our community on Slack" link on homepage is dead

### ISSUE THREAD

**Issue by CherryDT** [SoftwareBrothers/adminjs#1186] opened 2022-07-23 12:33 UTC
The big button "Join our community on Slack" on your [homepage](https://adminjs.co/) is no longer working:

![image](https://user-images.githubusercontent.com/6010463/180605053-674247ac-be2b-4844-9f4b-48ba70a94131.png)

**Comment by dziraf** [comment] 2022-07-23 12:37
CC @krzysztofstudniarek

**Comment by krzysztofstudniarek** [comment] 2022-07-23 12:43
Thanks for reporting, will take a look.

**Comment by krzysztofstudniarek** [comment] 2022-07-24 09:45
@CherryDT what kind of device did u use to access the link? 

I can't reproduce the issue on desktop, however Slack links does not work on mobile devices.

**Comment by CherryDT** [comment] 2022-07-24 09:51
Desktop with Chrome on Windows

**Comment by ddresch** [comment] 2022-07-24 21:15
Firefox Desktop (Mac) same - so no client issue.

**Comment by on21life** [comment] 2022-07-25 06:34
I have the same problem in MAC

**Comment by amoghgopinath** [comment] 2022-07-25 06:40
Facing same issue

**Comment by krzysztofstudniarek** [comment] 2022-07-25 06:48
@CherryDT, @on21life, @amoghgopinath could you check this link: https://join.slack.com/t/adminbro/shared_invite/zt-1c7z4k0v9-kBNAivB8lX3OWLWu6TLE7A ?

**Comment by amoghgopinath** [comment] 2022-07-25 08:28
> @CherryDT, @on21life, @amoghgopinath could you check this link: https://join.slack.com/t/adminbro/shared_invite/zt-1c7z4k0v9-kBNAivB8lX3OWLWu6TLE7A ?

yes it's working

**Comment by dziraf** [comment] 2022-07-25 13:53
Closing as resolved

**Closed by dziraf** 2022-07-25 13:53 UTC
