### ISSUE TITLE
NoResourceAdapterError on NestJs with two connected typeorm databases (mysql)

### ISSUE THREAD

**Issue by joris-calvat** [SoftwareBrothers/adminjs#878] opened 2021-07-12 13:12 UTC
Hi

Im' using NestJs + typeorm + 2 databases

When I use one database it works, but with 2 databases I get the following error

UnhandledPromiseRejectionWarning: NoResourceAdapterError: There are no adapters supporting one of the resource you provided

My code looks like

                TypeOrmModule.forRoot({
                    name: 'fs',
                    type: 'mysql', 
                    entities: [ModelA],
                    database: 'db1',
                    username: 'root',
                    password: 'admin',
                }),
                TypeOrmModule.forRoot({
                    name: 'auth',
                    type: 'mysql'
                    entities: [User],
                    database: 'db2',
                    username: 'root',
                    password: 'admin',
                }),
                AdminModule.createAdmin({
                    adminBroOptions: {
                        rootPath: '/admin',
                        resources: [ ModelA, User ],
                    },
                }),

Any idea ?

**Comment by dziraf** [comment] 2021-12-28 10:14
Closing because the issue is old. If you still need help, please reopen (preferrably in `adminjs-nestjs` repository).

**Closed by dziraf** 2021-12-28 10:14 UTC
