### ISSUE TITLE
Can't be used in express setup with app as return

### ISSUE THREAD

**Issue by developdeez** [SoftwareBrothers/adminjs#739] opened 2021-01-18 19:01 UTC
To use express in jest you need to return 'app' for testing which is normal.
With the setup from the docs theres no reasonable way to use AdminBro along with an express server that uses jest.
I even tried wrapping it in an anon async function and returning that to jest but it causes the server to become unresponsive.
When this is rememdied or if there is an example with express and mongo (exporting express app), I'll like to try again

**Comment by dziraf** [comment] 2021-12-28 10:39
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:39 UTC
