### ISSUE TITLE
From and To for DATES FILTER  are not translatable along with validation errors for uploadFile Feature

### ISSUE THREAD

**Issue by Amixengineer** [SoftwareBrothers/adminjs#827] opened 2021-04-27 09:27 UTC
Hello adminBro members, thanks for maintaining this great admin panel I think right now it's not possible to translate validation Errors of uploadFile feature and FROM, TO for date type in filter

keep up doing great job,🙌

**Comment by dziraf** [comment] 2021-12-28 10:27
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:27 UTC
