### ISSUE TITLE
Issue with showing referenced object

### ISSUE THREAD

**Issue by manish001in** [SoftwareBrothers/adminjs#828] opened 2021-04-29 13:02 UTC
So the error I am getting is There are no resources with given id: "workshop.timelines"\nThis is the list of all registered resources you can use.

* admin-bro@4.0.1
* admin-bro-expressjs@3.1.0
* admin-bro-mongoose@1.1.0
* mongoose@5.12.3
* mongodb@3.6.5

This is the resource I am trying to visualize in adminbro

```
const LearnerSchema = new mongoose.Schema(
  {
    workshops: [
      {
        workshop: {
          workshop_id: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'workshop',
          },
          code: {
            type: String,
          },
          timeline: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'workshop.timelines',
          },
        },
    ],
  { timestamps: true }
);
```

This is the workshop model:

```
const WorkshopSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
    },
    description: {
      type: String,
    },
    timelines: [
      {
        group: {
          type: Number,
        },
        city: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'city',
        },
        description: {
          type: String,
        },
        venue: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'venue',
        },
        month: {
          type: String,
        },
        start: {
          type: Date,
        },
        end: {
          type: Date,
        },
        registration_start: {
          type: Date,
        },
        registration_end: {
          type: Date,
        },
        registrations: {
          type: Number,
          default: 0,
        },
        registrations_cancelled: {
          type: Number,
          default: 0,
        },
        d_reg: {
          type: Number,
          default: 0,
        },
        classLink: {
          type: String,
          default: '',
        },
        status: {
          type: String,
          default: 'E',
        },
        resources: {
          _id: false,
          videoSessions: { type: Boolean, default: false },
        },
      },
    ],
    status: {
      type: String,
      enum: ['NEW', 'F', 'DISABLED'], //f = FEATURED
      default: 'NEW',
    },
  },
  { timestamps: true }
);

WorkshopSchema.index({ name: 'text', description: 'text' });

module.exports = Workshop = mongoose.model('workshop', WorkshopSchema);
```

Now, I have added both of these resources among others in my adminbro options, but when adminbro tries to fetch some records from the Collection, it fails with the error:

There are no resources with given id: "workshop.timelines"\nThis is the list of all registered resources you can use.

One more thing that might be affecting this issue is that in MongoDB the value of timelines in the workshop object is a mix of ObjectId and string, however I have tried converting all the object values to ObjectId but it still shows the same error.

Would really appreciate any help here.

**Comment by dziraf** [comment] 2021-04-29 14:54
AdminBro populates references using `ref` from the model, but the referenced model has to be defined as a resource while `workshop.timelines` is a field in Workshop schema and not a model/resource by itself. I'd try to create a Schema for Timeline and define it as an array of TimelineSchema in Workshop model but I'm not sure if it'll help

**Comment by manish001in** [comment] 2021-04-29 14:57
Thank you dziraf for the response.
That definitely makes sense. I was just wondering if there is a way to make it work the way it is currently structured? I thought maybe I was missing out or doing something wrong with my admin bro settings.

**Comment by manish001in** [comment] 2021-05-05 18:01
@dziraf Hi, I was trying to change my database and relevant code in the backend to make it work. Is there any way I can overwrite adminbro code to get what I desire? Could you guide me where to begin?

**Comment by Amritgrover** [comment] 2021-06-14 00:20
i am having the same problem don't know what to do

**Comment by manish001in** [comment] 2021-06-14 08:39
Hey @Amritgrover , there is no solution to this except changing your schema to remove the referenced object to its own collection.

**Comment by Amritgrover** [comment] 2021-06-17 13:27
can u pls tell me how to do it  i need it for my project

**Comment by manish001in** [comment] 2021-06-17 13:29
Please share some more detail about your exact issue and structure of database

**Comment by dziraf** [comment] 2021-12-28 10:26
Closing because the issue is old. If you still need help, please reopen.

**Comment by marcjoancr** [comment] 2021-12-28 12:57
> AdminBro populates references using `ref` from the model, but the referenced model has to be defined as a resource while `workshop.timelines` is a field in Workshop schema and not a model/resource by itself. I'd try to create a Schema for Timeline and define it as an array of TimelineSchema in Workshop model but I'm not sure if it'll help

Seems like that does not resolve the issue.
I have a Model 'CategoryService' with next schema:
```js
const CategoryServiceSchema = new Schema(
	{
		name: { type: LiteralSchema, required: true, select: true },
		description: { type: LiteralSchema, select: true }
	},
	{ timestamps: true }
);
```
And then another model 'Service' with the schema:
```js
const ServicesSchema = new Schema(
	{
		name: { type: LiteralSchema, required: true, select: true },
		description: { type: LiteralSchema, select: true },
		category: { type: Schema.Types.ObjectId, ref: 'CategoryService', select: true }
	},
	{ timestamps: true }
);
```
As you can see, both "name" and "description" are 'LiteralSchema' and not models, and then at the AdminJS I have both, Service and CategoryService, registered as resources like following:
```js
      {
        resource: Service,
        options: {
          navigation: establishmentNavigation,
          listProperties: ['name.es', 'category']
        }
      },
      {
        resource: CategoryService,
        options: {
          listProperties: ['name.es'],
          navigation: establishmentNavigation
        }
      },
```
And when I try to select a 'CategoryService' at 'Service's' edit page, it shows the next message:
```
Error: Objects are not valid as a React child (found: object with keys {es}). If you meant to render a collection of children, use an array instead. in div (created by Context.Consumer) in EmotionCssPropInternal (created by Option) in Option (created by Select) in div (created by Context.Consumer) in EmotionCssPropInternal (created by MenuList) in MenuList (created by MenuPlacer) in ScrollBlock (created by MenuPlacer) in NodeResolver (created by ScrollCaptor) in ScrollCaptor (created by ScrollCaptorSwitch) in ScrollCaptorSwitch (created by MenuPlacer) in div (created by Context.Consumer) in EmotionCssPropInternal (created by Menu) in Menu (created by MenuPlacer) in MenuPlacer (created by Select) in div (created by Context.Consumer) in EmotionCssPropInternal (created by SelectContainer) in SelectContainer (created by Select) in Select (created by StateManager) in StateManager (created by Async) in Async (created by Edit$6) in div (created by styled.div) in styled.div (created by Edit$6) in Edit$6 (created by WithTheme(Edit$6)) in WithTheme(Edit$6) (created by BasePropertyComponent) in section (created by styled.section) in styled.section (created by BasePropertyComponent) in ErrorBoundary (created by BasePropertyComponent) in BasePropertyComponent (created by New) in section (created by styled.section) in styled.section (created by New) in form (created by styled.section) in styled.section (created by New) in New (created by BaseActionComponent) in ErrorBoundary (created by BaseActionComponent) in BaseActionComponent (created by ResourceAction) in section (created by wrapper__StyledWrapper) in wrapper__StyledWrapper (created by Wrapper) in Wrapper (created by ResourceAction) in ResourceAction (created by ConnectFunction) in ConnectFunction (created by Context.Consumer) in Route (created by App) in Switch (created by App) in section (created by styled.section) in styled.section (created by App) in section (created by styled.section) in styled.section (created by App) in App in Router (created by BrowserRouter) in BrowserRouter in Unknown in Provider
See development console for more details...
```

**Comment by dziraf** [comment] 2021-12-28 13:11
If name is an object I think you'd have to define it as `mixed` type in resource `properties`:

```
      {
        resource: Service,
        options: {
          navigation: establishmentNavigation,
          listProperties: ['name.es', 'category'],
          properties: {
            name: { type: 'mixed' },
            'name.es': { type: 'string' }
          }
        }
      },
      {
        resource: CategoryService,
        options: {
          listProperties: ['name.es'],
          navigation: establishmentNavigation,
          properties: {
            name: { type: 'mixed' },
            'name.es': { type: 'string' }
          }
        }
      },
```

**Comment by marcjoancr** [comment] 2021-12-28 13:26
> If name is an object I think you'd have to define it as mixed type in resource properties:

With the following code:
```js
{
  resource: Service,
  options: {
    navigation: establishmentNavigation,
    listProperties: ['name.es', 'category'],
    properties: {
      name: { type: 'mixed' },
      'name.es': { type: 'string' },
      category: { reference: 'CategoryService' }
    }
  }
},
{
  resource: CategoryService,
  options: {
    listProperties: ['name.es'],
    navigation: establishmentNavigation,
    properties: {
      name: { type: 'mixed' },
      'name.es': { type: 'string' }
    }
  }
},
```
I still have the same error message:
![imagen](https://user-images.githubusercontent.com/14807142/147570795-ff0b109a-cfee-4b7c-a151-ba10bd403779.png)
And then, when I click on it, shows:
![imagen](https://user-images.githubusercontent.com/14807142/147570852-72407984-bf6f-4ac6-b467-f35c492ac594.png)

**Closed** 2022-06-15 11:05 UTC

**Comment by AgustinOberg** [comment] 2023-01-20 18:47
why do you close?
