### ISSUE TITLE
Currently datetime field is saved in DB with UTC format but while showing in UI admin js shows it in browsers timezone.

### ISSUE THREAD

**Issue by imaithal** [SoftwareBrothers/adminjs#978] opened 2022-01-12 06:32 UTC
How can i show it in UTC (same format how its saved in DB)

**Comment by jonathanmorris180** [comment] 2022-04-22 07:10
@imaithal Did you ever find a fix for this? I'm having the same issue in my production instance. Strangely, it doesn't happen on my local machine.

**Comment by SpaceOso** [comment] 2023-04-14 23:11
@imaithal did you ever find a solution to this?

**Comment by dziraf** [comment] 2023-04-18 13:11
This is an intended behaviour plus there's no easy way to allow to configure this. If you need to show datetimes in different timezones than user's local timezone you can create a custom component for that.

**Closed by dziraf** 2023-04-18 13:11 UTC
