### ISSUE TITLE
Trying to upload and returning "isValid() is not a function"

### ISSUE THREAD

**Issue by lucasnjsilva** [SoftwareBrothers/adminjs#869] opened 2021-06-26 11:13 UTC
**Describe the bug**
When trying to upload I'm getting an error saying that "isValid()" is not a function. Images are not saved either. 

The Code:

```
/** @type {AdminBro.After<AdminBro.ActionResponse>} */
const after = async (response, request, context) => {
  const { record, uploadImage } = context;

  if (record.isValid() && uploadImage) {
    const filePath = path.join('uploads', record.id().toString(), uploadImage.name);
    await fs.promises.mkdir(path.dirname(filePath), { recursive: true });

    await fs.promises.rename(uploadImage.path, filePath);

    await record.update({ profilePhotoLocation: `/${filePath}` });
  }
  return response;
};
```

The Error:
```
TypeError: record.isValid is not a function.
```

I followed the video from the JSCast channel. Other than that, the rest is working. The vídeo about upload system:
https://www.youtube.com/watch?v=7WtKcFqJHho

**Installed libraries and their versions**

    admin-bro@4.0.1,
    admin-bro-expressjs@2.1.1,
    admin-bro-mongoose@0.5.2,
    argon2@0.28.2,
    connect-mongo@4.4.1,
    express@4.17.1,
    express-formidable@1.2.0,
    express-session@1.17.2,
    mongoose@5.12.15

**Comment by dziraf** [comment] 2021-12-28 10:16
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:16 UTC
