### ISSUE TITLE
NoResourceAdapterError: There are no adapters supporting one of the resource you provided

### ISSUE THREAD

**Issue by Volodymyr-Zhuravlov** [SoftwareBrothers/adminjs#677] opened 2020-11-06 10:18 UTC
**Describe the bug**
when I try to set up AdminBro for Nest.js + typeorm I am getting the next error:
_UnhandledPromiseRejectionWarning: NoResourceAdapterError: There are no adapters supporting one of the resource you provided._

**Installed libraries and their versions**
 "admin-bro": "^3.3.1",
 "admin-bro-expressjs": "^2.1.1",
 "admin-bro-typeorm": "^0.1.6-alpha.9",
 "express": "^4.17.1",
 "express-formidable": "^1.2.0",
 "@nestjs/common": "7.0.0",
 "@nestjs/core": "7.0.0",
 "@nestjs/platform-express": "7.0.0",
 "@nestjs/typeorm": "7.0.0",

**To Reproduce**
Create base nest.js application and put next:
main.ts
```
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await setupAdminPanel(app);
  await app.listen(3000);
}
bootstrap();
```
token.entity.ts simple implementation
```
import AdminBro from "admin-bro";
import { Database, Resource } from '@admin-bro/typeorm';
import { validate } from 'class-validator'

AdminBro.registerAdapter({ Database, Resource });
Resource.validate = validate;

@Entity('token')
export class TokenEntity extends BaseEntity {
  @Column({ type: 'varchar' })
  accessToken: string;
}
```

**Expected behavior**
Start server properly

**Screenshots**
![Screenshot 2020-11-06 at 10 43 04](https://user-images.githubusercontent.com/57709779/98352721-100c7f80-2027-11eb-88f4-bab3cb7b45d2.png)

**AdminBroOptions with schema**
```
import { INestApplication } from '@nestjs/common';
import AdminBro from 'admin-bro';
import * as AdminBroExpress from 'admin-bro-expressjs';
import { BaseEntity } from '../shared';

export async function setupAdminPanel(app: INestApplication): Promise<void> {
  const adminBro = new AdminBro({
    resources: [{ resource: TokenEntity, options: {} }],
    rootPath: '/admin',
  });

  const router = AdminBroExpress.buildRouter(adminBro);
  app.use(adminBro.options.rootPath, router);

}
```

**Desktop:**
 - OS: macOS Catalina v10.15.7

**Additional context**
If I set up empty **resources: []**, the Server and Admin panel start properly.
Also, I tried to set up it by [official documentation](https://adminbro.com/module-@admin-bro_nestjs.html) but I have the same error.
Could you please, help me realize what is wrong?

**Comment by cloudratha** [comment] 2020-11-14 17:07
I suggest using the `@admin-bro/nestjs` package.

**Comment by SimonB407** [comment] 2020-11-26 14:07
You are probably using deprecated packages: admin-bro-typeorm & admin-bro-expressjs, you should use @admin-bro/typeorm & @admin-bro/express

**Comment by xinhash** [comment] 2020-12-08 08:01
```ts
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigModule, ConfigService } from '@nestjs/config';
import AdminBro from 'admin-bro';
import { AdminModule as AdminBroModule } from '@admin-bro/nestjs';
import { Database, Resource } from '@admin-bro/typeorm';
import Post from 'src/posts/posts.entity';
AdminBro.registerAdapter({ Database, Resource });

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        type: 'postgres',
        host: configService.get('POSTGRES_HOST'),
        port: configService.get('POSTGRES_PORT'),
        username: configService.get('POSTGRES_USER'),
        password: configService.get('POSTGRES_PASSWORD'),
        database: configService.get('POSTGRES_DB'),
        entities: [__dirname + '/../**/*.entity.ts'],
        synchronize: true,
      }),
    }),
    AdminBroModule.createAdmin({
      adminBroOptions: {
        rootPath: '/admin',
        resources: [Post],
      },
    } as any)
  ],
})
export class DatabaseModule {}
```
<img width="1073" alt="Screenshot 2020-12-08 at 1 30 38 PM" src="https://user-images.githubusercontent.com/13267635/101456115-92a39a00-3959-11eb-8609-9ed80c0f68fa.png">

When I pass ``resource: []`` I'm able to access ``/admin`` route

**Comment by dziraf** [comment] 2020-12-08 08:36
try to `await connection()` (typeorm connection) before setting up admin route

**Comment by uapasha** [comment] 2020-12-11 19:48
@Volodymyr-Zhuravlov  @xinhash your Entity should extend BaseEntity.

```
import {
    BaseEntity,
    Entity
} from 'typeorm';

@Entity()
export class Person extends BaseEntity


```


Would be good to mention this in the docs... :)

**Comment by ArianaGandhi** [comment] 2021-01-02 13:16
@uapasha any idea how to fix this on express/mongoose?

**Comment by SimonB407** [comment] 2021-01-04 08:45
@ArianaGandhi please send code snippet with initialization of admin module, because mongoose and typeorm usages are very different.

**Comment by maxpeterson** [comment] 2021-01-07 13:32
I am facing a similar `NoResourceAdapterError` issue with `nestjs` and `mongoose`

```
import { Module } from '@nestjs/common';
import { MongooseModule, getModelToken } from '@nestjs/mongoose';
import { APP_INTERCEPTOR } from '@nestjs/core';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { RavenModule, RavenInterceptor } from 'nest-raven';
import AdminBro from 'admin-bro';
import { AdminModule } from '@admin-bro/nestjs';
import { Model } from 'mongoose';
import { Database, Resource } from '@admin-bro/mongoose';
import { PolicyDocument } from './policies/interfaces/policy.interface';

AdminBro.registerAdapter({ Database, Resource });

@Module({
  imports: [
    AssessmentModule,
    AuthModule,
    ConfigModule.forRoot({
      envFilePath: '.env',
      validationSchema,
      validationOptions: {
        allowUnknown: true,
        abortEarly: false,
      },
    }),
    MongooseModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (config: ConfigService) => ({
        uri: config.get('DB_CONNECTION_URL'),
        useNewUrlParser: true,
        useUnifiedTopology: true,
        useFindAndModify: false,
      }),
      inject: [ConfigService],
    }),
    AdminModule.createAdminAsync({
      useFactory: (policiesModel: Model<PolicyDocument>) => ({
        adminBroOptions: {
          rootPath: '/admin',
          resources: [
            { resource: policiesModel },
          ],
        },
      }),
    }),
    PoliciesModule,
  ],
  controllers: [AppController],
  providers: [
    {
      provide: APP_INTERCEPTOR,
      useValue: new RavenInterceptor(),
    },
    AppService,
    S3Service,
  ],
})
```

**Comment by SimonB407** [comment] 2021-01-07 15:50
@maxpeterson please read Advanced Techniques on [nestjs plugin description](https://adminbro.com/module-@admin-bro_nestjs.html). You have to inject models that you want to use in adminBro. useFactory does not know what policiesModel is automatically.

**Comment by maxpeterson** [comment] 2021-01-08 09:02
Thanks @SimonB407. I couldn't get it to work using `getModelToken` based on the example, however I was able to get it working using a provider / service (where the mongoose models were injected).

I am now facing a "Server error. Please try again later." issues with the authentication!

**Comment by dbrody** [comment] 2021-01-19 19:55
I was getting this error too and found that its due to this line:

https://github.com/SoftwareBrothers/admin-bro-typeorm/blob/7ff78547db5eb0c8344692c92577a973593437d7/src/Resource.ts#L199

Basically `@admin-bro/typeorm` is checking if the Model is a TypeOrm Model by seeing if it has a repository associated with it. By default there is no repository on it. By setting the connection on the model the repository is then found.

This seems to work for me:
```typescript
const { createConnection } from 'typeorm'
const connection = await createConnection(db_config)
await User.useConnection(connection)
```

**Comment by IBRAHIMDANS** [comment] 2021-02-12 16:33
i have same error

**Comment by maschinenlesbareregierung** [comment] 2021-02-12 21:58
this error  needs a bit mor explanation. I have the same poblem with a pretty default setup (except the external npm repo that holds my typeorm model) and can not get it to work. maybe provide a non mongoose and more typeorm/sql type example? That would be quite helpful. Thanks

**Comment by brams223** [comment] 2021-02-15 11:49
I have the same bug with nestjs typeorm postges no example available? 
thanks

**Comment by 0fuz** [comment] 2021-02-19 18:32
> @Volodymyr-Zhuravlov @xinhash your Entity should extend BaseEntity.
> 
> ```
> import {
>     BaseEntity,
>     Entity
> } from 'typeorm';
> 
> @Entity()
> export class Person extends BaseEntity
> ```
> 
> Would be good to mention this in the docs... :)

@brams223 try follow suggestion above. It helped me with "nestjs typeorm sqlite"

**Comment by IBRAHIMDANS** [comment] 2021-02-19 18:35
Hello @0fuz  i have a bug with `.entry.js ` have you a anwser for me  🙃

**Comment by IBRAHIMDANS** [comment] 2021-02-19 18:36
> Hello @0fuz i have a bug with `.entry.js ` have you a anwser for me 🙃

.entry.js:1 Uncaught TypeError: Cannot set property 'UserComponents' of undefined

**Comment by 0fuz** [comment] 2021-02-23 08:47
@IBRAHIMDANS probably its mistake with .js and .ts code. ".entry.js:1" error on first line means something wrong with 'import' statements. Haven't another ideas(

**Comment by yconselvan** [comment] 2021-04-03 02:27
i was struggling to make it work with typeorm and postgres, but @uapasha comment was helpfull.

after extending BaseEntity, typeorm configuration is simple

**Comment by insomenia-woobyeong** [comment] 2021-06-05 04:18
```
import { Database, Resource } from '@admin-bro/typeorm';

AdminBro.registerAdapter({ Database, Resource });
```

check this

**Comment by nomanbiniqbal** [comment] 2021-06-22 10:50
Facing same issue with  '@admin-bro/sequelize'
```
import { Database, Resource } from '@admin-bro/sequelize';
import { AdminModule } from '@admin-bro/nestjs';
AdminBro.registerAdapter({ Database, Resource });


SequelizeModule.forRoot({
      dialect: 'mysql',
      host: process.env.DATABASE_HOST,
      port: +process.env.DATABASE_PORT,
      username: process.env.DATABASE_USERNAME,
      password: process.env.DATABASE_PASSWORD,
      database: process.env.DATABASE_NAME,
      models: [__dirname + '/**/*.model.ts'],
      logging: console.log
    }),


    AdminModule.createAdmin({ adminBroOptions: { rootPath: '/admin', resources: [{ resource: User, options: {} }], } }),
```

**Comment by gottaloveit** [comment] 2021-08-23 23:41
I get same problem with sequelize

```javascript

const express = require('express');
const app = express();

const AdminBro = require('admin-bro');
const AdminBroExpress = require('@admin-bro/express');
const { Database, Resource } = require('@admin-bro/sequelize');
AdminBro.registerAdapter({ Database, Resource });

const db = require('./src/models');
const Game = require('./src/models/game');

const adminBro = new AdminBro({
  databases: [db],
  rootPath: '/admin',
  resources: [Game]
})

const router = AdminBroExpress.buildRouter(adminBro)
app.use(adminBro.options.rootPath, router)
```
error:
```
/home/brian/raffle/node_modules/admin-bro/lib/backend/utils/resources-factory/resources-factory.js:99
        throw new NoResourceAdapterError(resourceObject);
        ^

NoResourceAdapterError: There are no adapters supporting one of the resource you provided
    at /home/brian/raffle/node_modules/admin-bro/lib/backend/utils/resources-factory/resources-factory.js:99:15
    at Array.map (<anonymous>)
    at ResourcesFactory._convertResources (/home/brian/raffle/node_modules/admin-bro/lib/backend/utils/resources-factory/resources-factory.js:93:22)
    at ResourcesFactory.buildResources (/home/brian/raffle/node_modules/admin-bro/lib/backend/utils/resources-factory/resources-factory.js:48:35)
    at new AdminBro (/home/brian/raffle/node_modules/admin-bro/lib/admin-bro.js:101:39)
    at Object.<anonymous> (/home/brian/raffle/index.js:15:18)
```

But when I take out the resources config, everything works fine
```javascript

const express = require('express');
const app = express();

const AdminBro = require('admin-bro');
const AdminBroExpress = require('@admin-bro/express');
const { Database, Resource } = require('@admin-bro/sequelize');
AdminBro.registerAdapter({ Database, Resource });

const db = require('./src/models');
const Game = require('./src/models/game');

const adminBro = new AdminBro({
  databases: [db],
  rootPath: '/admin'
})

const router = AdminBroExpress.buildRouter(adminBro)
app.use(adminBro.options.rootPath, router)
```

**Comment by dziraf** [comment] 2021-12-28 10:48
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:48 UTC
Labels: help wanted

**Comment by Tushant** [comment] 2022-09-17 03:48
```javascript
import AdminJS from 'adminjs';
import { AdminModule } from '@adminjs/nestjs';
import { Resource, Database } from '@adminjs/prisma';
import { getDMMF } from '@prisma/internals';

AdminJS.registerAdapter({ Resource, Database });

AdminModule.createAdminAsync({
      imports: [PrismaModule],
      inject: [PrismaService],
      useFactory: async (prisma: PrismaService) => {
        const prismaSchemaPath = path.join('./prisma', 'schema.prisma');
        const file = fs.readFileSync(prismaSchemaPath, 'utf-8');
        const dmmf = getDMMF({ datamodel: file });
        return {
          adminJsOptions: {
            rootPath: '/admin',
            resources: [
              {
                resource: {
                  model: (await dmmf).datamodel.models,
                  client: prisma,
                },
                options: {},
              },
            ],
          },
          auth: {
            authenticate,
            cookieName: 'adminjs',
            cookiePassword: 'secret',
          },
          sessionOptions: {
            resave: true,
            saveUninitialized: true,
            secret: 'secret',
          },
        };
      },
    }),
```

I am also getting similar issue. I am using prisma 4.

**Comment by JuanPedroPontVerges** [comment] 2023-01-20 18:56
Im getting same error even though i do extend my entities to BaseEntity.

`
NoResourceAdapterError: There are no adapters supporting one of the resource you provided
    at /usr/src/app/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:99:15
    at Array.map (<anonymous>)
    at ResourcesFactory._convertResources (/usr/src/app/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:93:22)
    at ResourcesFactory.buildResources (/usr/src/app/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:48:35)
    at new AdminJS (/usr/src/app/node_modules/adminjs/lib/adminjs.js:114:39)
    at AdminModule.onModuleInit (/usr/src/app/node_modules/@adminjs/nestjs/build/admin.module.js:72:23)
    at Object.callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NestApplication.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:169:13)
    at async NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:97:9) {
  resource: [class Organization extends BaseEntity]
`

This is my app.module.ts

``

**Comment by yevhenprudnik** [comment] 2023-02-10 14:00
```js 
'use strict';

require('dotenv').config();

const Fastify = require('fastify');

const AdminJSFastify = require('@adminjs/fastify');
const AdminJS = require('adminjs');
const AdminJSObjection = require('@adminjs/objection');
const Questions = require('./DB/models/question.model');

AdminJS.registerAdapter({
  Resource: AdminJSObjection.Resource,
  Database: AdminJSObjection.Database,
});

const start = async () => {
  const app = Fastify({
    logger: false,
    pluginTimeout: 10000,
  });

  await app.register(require('./app'));

  const admin = new AdminJS({
    resources: [Questions],
    rootPath: '/admin',
  });

  AdminJSFastify.buildRouter(admin, app);

  app.listen(
    { port: process.env.PORT || 8080, host: process.env.HOST || '0.0.0.0' },
    err => {
      if (err) {
        app.log.error(err);
        process.exit(1);
      }
    }
  );
};

start();
```
Error:
```
NoResourceAdapterError: There are no adapters supporting one of the resource you provided
    at /Users/jekaprudnik/Desktop/MProjects/Estimate-Calculator/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:101:15
    at Array.map (<anonymous>)
    at ResourcesFactory._convertResources (/Users/jekaprudnik/Desktop/MProjects/Estimate-Calculator/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:94:22)
    at ResourcesFactory.buildResources (/Users/jekaprudnik/Desktop/MProjects/Estimate-Calculator/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:48:35)
    at new AdminJS (/Users/jekaprudnik/Desktop/MProjects/Estimate-Calculator/node_modules/adminjs/lib/adminjs.js:114:39)
    at start (/Users/jekaprudnik/Desktop/MProjects/Estimate-Calculator/server.js:25:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  resource: [class Questions extends BaseModel]
}
```

Having the same issue with fastify and objection.

**Comment by MohammadKurjieh** [comment] 2023-03-15 15:55
Any updates on this issue? I am facing it on NestJS + Prisma 4.

**Comment by devvspaces** [comment] 2023-03-21 05:33
@MohammadKurjieh,I later found a solution for Nestjs and Prisma. I provided an answer in this [StackOverflow question](https://stackoverflow.com/a/75797605/11681208).
