### ISSUE TITLE
Resource fields don't show typing informations

### ISSUE THREAD

**Issue by asynched** [SoftwareBrothers/adminjs#1173] opened 2022-07-17 04:17 UTC
**Describe the bug**
No typing information is showed on editors when trying to add a new resource to the resource array in the `AdminJS` instance.

**Installed libraries and their versions**

- adminjs@^6.0.0
- @adminjs/express@^5.0.0
- @adminjs/mongoose@^3.0.0

**To Reproduce**
1. Create a new AdminJS instance
2. In the property `resource` of the options object, add an array with a resource
3. Typing won't be available for the resource item

> I've created a repo for reproducing the bug: https://github.com/asynched/adminjs-resource-fields-repro

**Expected behavior**
Expected to have typing schema for a resource entry in the array of resources.

**Screenshots**
![image](https://user-images.githubusercontent.com/64004309/179383516-f0ee770c-7c69-4086-9df8-74eb27f5c2f9.png)

**Additional context**
The problem seems to be related to the `AdminJSOptions` type definition, where the resource type is `Array<ResourceWithOptions | any>`, removing the `any` type seems to fix the problem (as the screenshot below shows).

![image](https://user-images.githubusercontent.com/64004309/179383557-ead3af3d-d2cf-4deb-947a-7482fd0e94f1.png)

The editor I'm currently using is VSCode, I don't know if the problem is specific to VSCode.

**Comment by krzysztofstudniarek** [comment] 2022-08-16 09:52
This is a duplicate of https://github.com/SoftwareBrothers/adminjs/issues/656

**Closed by krzysztofstudniarek** 2022-08-16 09:52 UTC
