### ISSUE TITLE
question about properties restrictions

### ISSUE THREAD

**Issue by baterry2** [SoftwareBrothers/adminjs#767] opened 2021-02-14 10:56 UTC
Hi, not found solution of my case, and decide to create new, sorry if this duplicated. I have 2 admin roles, one is full access, and second is restricted. Depends on role, can we show/hide properties for editing?  isVisible/isAccessibe, etc... they only works with sync boolean values. Sory for grammar errors, English is not my native . Thanks

**Comment by dziraf** [comment] 2021-12-28 10:35
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:35 UTC

**Comment by buffless-matt** [comment] 2022-06-20 03:59
I think @baterry2 is asking about the following (which I'd also like to ask about):

Can we have the equivalent of action [isAccessible](https://docs.adminjs.co/Action.html#isAccessible) and action [isVisible](https://docs.adminjs.co/Action.html#isVisible), but for properties?

E.g. If we have an RBAC role that has more permissions than another, how can we have two or more sets of [showProperties](https://docs.adminjs.co/ResourceOptions.html#showProperties), [listProperties](https://docs.adminjs.co/ResourceOptions.html#listProperties), etc. for a resource, depending on the role of the currently authenticated user?

This doesn't appear to be supported, is that correct? If so, are there plans to add support for such capability?

The only workaround that comes to mind is to create a separate resource per RBAC role.
