### ISSUE TITLE
Huge bundle included

### ISSUE THREAD

**Issue by JanChodorowski** [SoftwareBrothers/adminjs#876] opened 2021-07-11 20:12 UTC
Hi guys!
I was playing with the latest version of your panel and discovered that 25.6MB `design-system.bundle.js` is being included. 

"@adminjs/express": "^4.0.0",
 "adminjs": "^5.0.1",

**Comment by dziraf** [comment] 2021-12-28 10:15
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:15 UTC
