### ISSUE TITLE
.entry.js:1 Uncaught TypeError: Cannot set property 'UserComponents' of undefined

### ISSUE THREAD

**Issue by carmonac** [SoftwareBrothers/adminjs#779] opened 2021-02-28 02:01 UTC
**Describe the bug**
I've installed AdminBro for nest with typeorm adapter and when I run the project I get a blank screen when i try to access to the dashboard

**Installed libraries and their versions**

* @admin-bro/typeorm
* @admin-bro/nestjs
* admin-bro
* @admin-bro/express
* express-formidable

**To Reproduce**
1. Implement AdminBro following the documentation
2. Run project
3. Access /admin in browser

**Expected behavior**
See dashboard.

**Screenshots**

<img src="https://i.ibb.co/LJfnQpt/Captura-de-pantalla-2021-02-28-a-las-2-29-53.png" alt="Captura-de-pantalla-2021-02-28-a-las-2-29-53" border="0">

**AdminBroOptions with schema**
```
@Module({
  imports: [
    AdminModule.createAdmin({
      adminBroOptions: {
        rootPath: '/admin',
        resources: [User],
      }
    }),
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        type: 'mongodb',
        host: configService.get('DATABASE_HOST'),
        database: configService.get('DATABASE_NAME'),
        entities: [User],
        useUnifiedTopology: true,
        synchronize: true,
      }),
      inject: [ConfigService],
    }),
    UserModule, 
    AuthModule
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

-------

```
import { BaseEntity, Column, Entity, ObjectID, ObjectIdColumn, BeforeInsert, Index } from 'typeorm';
import { Plan, UserRole } from '../common';
import * as bcrypt from 'bcrypt';
import { Database, Resource } from '@admin-bro/typeorm';
import { validate } from 'class-validator'
import AdminBro from 'admin-bro';
import * as AdminBroExpress from '@admin-bro/express'
Resource.validate = validate;
AdminBro.registerAdapter({ Database, Resource });

@Entity()
export class User extends BaseEntity {
    @ObjectIdColumn()
    id: ObjectID;

    @Column()
    @Index({ unique: true })
    name: string;

    @Column()
    @Index({ unique: true })
    email: string;
...
```

**Comment by darkmavis1980** [comment] 2021-03-10 10:42
I have the same exact issue, just installed on a new project I'm working on, and while I don't get any errors from the node.js part, the client is just showing me a blank page.

**Comment by chirdeeptomar** [comment] 2021-04-18 17:40
#https://github.com/SoftwareBrothers/admin-bro/issues/729

**Comment by dziraf** [comment] 2021-12-28 10:32
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:32 UTC
