### ISSUE TITLE
Save a new record from a custom component

### ISSUE THREAD

**Issue by alvaropaco** [SoftwareBrothers/adminjs#832] opened 2021-04-30 21:00 UTC
I'm very dummy with AdminBro yet but, I'm trying to write a custom component to a resource "new" action. I want to have a component with a form with some text fields and when I submit this I want to that form to be summited to my action "after" interceptor to treat the data. My component implementation:
```
import React from 'react';
import { ActionProps } from 'admin-bro';
import {
  Box, Label, Input, Button,
} from '@admin-bro/design-system';

export default function (props: ActionProps) {
  const { resource } = props;

  const render = () => (resource.editProperties.map((property) => (
    <Box width={1}>
      <Label htmlFor={property.name}>{ property.name }</Label>
      <Input
        id={property.name}
        name={property.name}
        width={1}
        type={property.type}
      />
    </Box>
  )));

  return (
    <Box variant="white" width={1}>
      <form>
        { render() }
        <Button type="submit">Submit</Button>
      </form>
    </Box>
  );
}

```
I've tried to do that with `api.resourceAction`, but the request take a while and then returns an error:
```
api.resourceAction(
    {
      resourceId: 'user',
      actionName: 'new',
      method: 'post',
      data,
    },
  ).then((response) => {
    console.log(response);
    debugger;
  })
```
Returns:
```
Error: Request aborted
    at IncomingMessage.<anonymous> (/home/alvaro/HealthIQ/hiqfe_mono/packages/projects/crm/admin/node_modules/formidable/lib/incoming_form.js:122:19)
    at IncomingMessage.emit (events.js:314:20)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at abortIncoming (_http_server.js:533:9)
    at socketOnClose (_http_server.js:526:3)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at TCP.<anonymous> (net.js:675:12)
    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)
```

How to do that, and what's the best way to do that?

**Comment by dziraf** [comment] 2021-12-28 10:17
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:17 UTC
