### ISSUE TITLE
Server Side request forgery

### ISSUE THREAD

**Issue by shubhambhartiya08** [SoftwareBrothers/adminjs#825] opened 2021-04-27 08:27 UTC
Hello,

Kindly help us in resolving this.
![ssrf4](https://user-images.githubusercontent.com/31841628/116210426-7c5b7680-a760-11eb-9985-d52ca59c1552.png)
![ssrf3](https://user-images.githubusercontent.com/31841628/116210432-7d8ca380-a760-11eb-9ba6-356a8267046e.png)
![ssrf2](https://user-images.githubusercontent.com/31841628/116210437-7e253a00-a760-11eb-9588-872528c68800.png)
![ssrf1](https://user-images.githubusercontent.com/31841628/116210441-7ebdd080-a760-11eb-88e4-88c82d3a0c0b.png)

**Comment by dziraf** [comment] 2021-12-28 10:27
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:27 UTC
