### ISSUE TITLE
Custom pages label uses key

### ISSUE THREAD

**Issue by JSRossiter** [SoftwareBrothers/adminjs#670] opened 2020-11-02 18:41 UTC
Upgrading to 3.3.1 from 3.2.5 causes custom page labels to use the untranslated key from the options (usually camel case). It looks like previously translateLabel was used, and could be fixed by being added to https://github.com/SoftwareBrothers/admin-bro/blob/master/src/frontend/components/app/sidebar/sidebar-pages.tsx#L32

I can work around it by changing the keys be appropriately cased using square bracket notation but I suspect this wasn't intentional. I also noticed the docs (https://adminbro.com/AdminBroOptions.html#pages) make reference to using a label option which doesn't seem to be implemented.

**Comment by lunardidev** [comment] 2020-11-04 22:02
Same problem here. Example:

pages: {
customPage: {
label: "Custom page",
handler: async (request, response, context) => {
return {
text: 'I am fetched from the backend',
}
},
component: AdminBro.bundle("./reactjs/components/dashboard/Dashboard.tsx"),
},
anotherPage: {
label: "TypeScript page",
component: AdminBro.bundle("./reactjs/components/dashboard/Dashboard.tsx"),
}
},

**Comment by bgruszka** [comment] 2021-01-27 10:57
@JSRossiter how did you solve it? I've the same problem with pages label translations.

**Comment by freeworlder** [comment] 2021-04-20 21:28
Is there a solution to this? Label prop on pages doesn't work at the moment

**Comment by dziraf** [comment] 2021-12-28 10:49
Closing because the issue is old. If you still need help, please reopen.

**Closed by dziraf** 2021-12-28 10:49 UTC
